export const GET_TASKS_START = 'GET_TASKS_START';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR';

export const DELETE_TASK_START = 'DELETE_TASK_START';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';

export const EDIT_TASK_START = 'EDIT_TASK_START';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const EDIT_TASK_ERROR = 'EDIT_TASK_ERROR';

export const GET_SINGLE_TASK_START = 'GET_SINGLE_TASK_START';
export const GET_SINGLE_TASK_SUCCESS = 'GET_SINGLE_TASK_SUCCESS';
export const GET_SINGLE_TASK_ERROR = 'GET_SINGLE_TASK_ERROR';

export const ADD_TASK = 'ADD_TASK';
export const SET_TASKS = 'SET_TASK';
